language: python
sudo: required
# https://docs.travis-ci.com/user/ci-environment/ to get a modern gcc etc
dist: trusty

# notes from http://conda.pydata.org/docs/travis.html
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same. 
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - export RANDOM_ID=`python -c "from random import choice; print(''.join([choice('1234567890') for i in range(6)]))"`; 
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - printenv TRAVIS_PULL_REQUEST
  - printenv TRAVIS_PULL_REQUEST_BRANCH
  - printenv TRAVIS_COMMIT
  - printenv TRAVIS_BRANCH
  - printenv
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pytest cython nose boto3 PyYAML Click pytest numba
  - source activate test-environment
  - pip install glob2 pylint tornado awscli

before_script:
  - export EPOCH_STAMP=`date +%s`
  - export BUILD_GUID=`echo $TRAVIS_JOB_NUMBER | sed 's/\./_/g'`_${EPOCH_STAMP}_${RANDOM_ID}
  - echo CLEAN BUILD ID IS $BUILD_GUID

script:
    pytest -v --traceback tests/simple_test

after_script:
  # always make sure we do this cleanup if we can
  - aws s3 rm --recursive s3://numpywrentest/pywren.linalg
after_failure:
  - aws s3 rm --recursive s3://numpywrentest/pywren.linalg

