language: python
sudo: required
dist: trusty
python:
- '3.6'
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- export RANDOM_ID=`python -c "from random import choice; print(''.join([choice('1234567890')
  for i in range(6)]))"`;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- printenv TRAVIS_PULL_REQUEST
- printenv TRAVIS_PULL_REQUEST_BRANCH
- printenv TRAVIS_COMMIT
- printenv TRAVIS_BRANCH
- printenv
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pytest cython
  nose boto3 PyYAML Click pytest numba scipy sklearn
- source activate test-environment
- pip install glob2 pylint tornado awscli sklearn
before_script:
- export EPOCH_STAMP=`date +%s`
- export BUILD_GUID=`echo $TRAVIS_JOB_NUMBER | sed 's/\./_/g'`_${EPOCH_STAMP}_${RANDOM_ID}
- echo CLEAN BUILD ID IS $BUILD_GUID
script: pytest -v --fulltrace tests/simple_tests.py
after_script:
- aws s3 rm --recursive s3://numpywrentest/pywren.linalg
after_failure:
- aws s3 rm --recursive s3://numpywrentest/pywren.linalg
env:
  global:
    secure: HI3oA61BGpQs/qkrC84BKb5HscOrmzFPQpCOM3Cc15mDM7U+LB7ICRUMbTX9WQ7ustkhRVOzef6xP0Hac6ntf7MCVVeDKyAH2jaFcbKxVIK9lIYKNaBUynhcjDTspgk7zIKnJKIQ5LN8Bza60Rj39JnwMK/rJ04ChQIB1392h5EgtL6oy14hVy5XZvI/hs6JfVu3wQ6szP9M8cylKPyJf/SoDzdJhk5T9IZtV01DAI7j/o0FfDddxlrRuLogAC/Z2z7bGn3wYDAVSORpPygwYpCT2lknjYa4vzEMMmENDtZ+VhuMQPqbASPgeaWhMrs3eyUmVqPNHQVCpKcIlwQpjHf5apy1FobSnNW16O9/QdxQVnG3lRMSvx6KimNKFg8CmigwiK2peKpGGtYz3dNr0gfrzsZcPJuWgSMjcnC0JI8zxLK/g1ZBoWujYMmDw1bMct00YLwF/zxqbsn7WosEc5omTRsEc4/8rQcA+s4ceSnRN3aldtivgzVyII47OGpQRpTfSyy+NH3mBpLEvA+dIpVs6tbMqTOoBWFgb+Jbx0MTfX9dAfF5Py/PFvyTzPHZrAI8XgagxlfSi4t+It84Wecjf8ZehLJIzByxKJhjm8PivVMxt5USH3b3ZDz+iLhqPmsPOceF9RwbHDSbhh4Th15cHKbLYmRbtuuxTAAz804=
